name = "hari-portfolio"
compatibility_date = "2023-12-01"

[build]
command = "bun run build"

[site]
bucket = "build"

[build.upload]
format = "directory"
dir = "build"

# Pages specific config
pages_build_output_dir = "build" 