name = "hari-portfolio"
compatibility_date = "2023-12-01"

# Specify the build output directory explicitly - this is required for Pages
pages_build_output_dir = "build"

[build]
command = "bun run build"

[site]
bucket = "build"

[env.production]
name = "hari-portfolio"
route = "*/*" 