name = "hari-portfolio"
compatibility_date = "2024-02-01"

main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2024-02-01"

workers_dev = false
build = "bun run build"
node_compat = true
